# Generated by Django 4.0 on 2021-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guantes',
            name='esPremium',
            field=models.BooleanField(null=True),
        ),
    ]
