# Generated by Django 4.0 on 2021-12-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid', '0002_guantes_espremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='oximetros',
            name='esImportado',
            field=models.BooleanField(null=True),
        ),
    ]
